name: black Lint

on: [pull_request]

jobs:
  black-lint:
    runs-on: ubuntu-latest
    name: black Lint
    steps:
      - uses: actions/checkout@v3
      - uses: psf/black@stable
        with:
          options: "--safe --line-length=100 --preview"
